---
title: "Data Science"
---

```{r include=FALSE}
source("https://raw.githubusercontent.com/kctolli/kctolli.github.io/master/site_libs/script.R")
load_libraries()

pander('<link rel="stylesheet" href="https://raw.githubusercontent.com/kctolli/kctolli.github.io/master/site_libs/site.css">')
pander('<style>img {display: block; margin-left: auto; margin-right: auto; width: 125%;}</style>')
```

```{r main}
print_pic("https://secure.meetupstatic.com/photos/event/d/7/4/b/600_482695115.jpeg")
print_newline()
print_h4("Interdisciplinary field that uses scientific methods, processes, algorithms, and systems to extract knowledge and insights from many structural and unstructured data.")
print_newline()
pander("--- Related to [Data Analytics](https://en.wikipedia.org/wiki/Data_analysis), [Data Mining](https://en.wikipedia.org/wiki/Data_mining), [Big Data](https://en.wikipedia.org/wiki/Big_data), [Regression](https://en.wikipedia.org/wiki/Regression_analysis), [Deep Learning](https://en.wikipedia.org/wiki/Deep_learning), [Machine Learning](https://en.wikipedia.org/wiki/Machine_learning), and [Business Intelligence](https://en.wikipedia.org/wiki/Business_intelligence).")
```